version: "3.3"
services:
 apache-XD:
  container_name: asir_apache
  image: php:7.2-apache
  ports:
    - "80:80"
    - "8000:8000"
  volumes:
    - /home/asir2a/Escritorio/SRI/tuto/server/html:/var/www/html:ro
    - /home/asir2a/Escritorio/SRI/tuto/server/apache2:/etc/apache2
volumes:
  configApache:
